---
title: "DSCI561 - Final Project - Figures for Paper"
author: "Team 2"
date: "12/2/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readr)
library(gridExtra)
library(reshape2)
```

```{r}
df = read_csv("../data/df.csv")
```


Creating boxplots of our initial variables.

```{r}
dfTrain = df[df$validate==0,]
```

```{r, fig.width=10, fig.height=3, echo=FALSE}
pSum = ggplot(dfTrain, aes(classification, sum, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("sum") + theme(legend.position = "none")

pZeroes = ggplot(dfTrain, aes(classification, zeroes, fill=factor(classification))) +  geom_boxplot()+ ggtitle("zeroes") + theme(legend.position = "none")

pNorm = ggplot(dfTrain, aes(classification, norm, fill=factor(classification))) +  geom_boxplot() + ggtitle("norm")  + theme(legend.position = "none")

grid.arrange(pSum, pZeroes, pNorm, nrow=1)
```

```{r, fig.width=10, fig.height=3, echo=FALSE}
pq1 = ggplot(dfTrain, aes(classification, q1, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("q1") + theme(legend.position = "none")

pq3 = ggplot(dfTrain, aes(classification, q3, fill=factor(classification))) +  geom_boxplot()+ ggtitle("q3") + theme(legend.position = "none")

piqr = ggplot(dfTrain, aes(classification, iqr, fill=factor(classification))) +  geom_boxplot() + ggtitle("iqr")  + theme(legend.position = "none")

grid.arrange(pq1, pq3, piqr, nrow=1)
```

```{r, fig.width=10, fig.height=3, echo=FALSE}
pmin = ggplot(dfTrain, aes(classification, min, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("min") + theme(legend.position = "none")

pmax = ggplot(dfTrain, aes(classification, max, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("max") + theme(legend.position = "none")

pstd = ggplot(dfTrain, aes(classification, std, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("std") + theme(legend.position = "none")

grid.arrange(pmin, pmax, pstd, nrow=1)
```

```{r, fig.width=10, fig.height=3, echo=FALSE}
pmean = ggplot(dfTrain, aes(classification, mean, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("mean") + theme(legend.position = "none")

pmed = ggplot(dfTrain, aes(classification, med, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("median") + theme(legend.position = "none")

paboveMeanCount = ggplot(dfTrain, aes(classification, aboveMeanCount, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("aboveMeanCount") + theme(legend.position = "none")

grid.arrange(pmean, pmed, paboveMeanCount, nrow=1)
```

```{r, fig.width=10, fig.height=3, echo=FALSE}
prange = ggplot(dfTrain, aes(classification, range, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("range") + theme(legend.position = "none")

pskew = ggplot(dfTrain, aes(classification, skew, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("skew") + theme(legend.position = "none")

pkurtosis = ggplot(dfTrain, aes(classification, kurtosis, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("kurtosis") + theme(legend.position = "none")

grid.arrange(prange, pskew, pkurtosis, nrow=1)
```

```{r, fig.width=10, fig.height=3, echo=FALSE}
pentropy = ggplot(dfTrain, aes(classification, entropy, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("entropy") + theme(legend.position = "none")

pcontourAvgLength = ggplot(dfTrain, aes(classification, contourAvgLength, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("contourAvgLength") + theme(legend.position = "none")

pcontourCountLSD = ggplot(dfTrain, aes(classification, contourCountLSD, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("contourCountLSD") + theme(legend.position = "none")

grid.arrange(pentropy, pcontourAvgLength, pcontourCountLSD, nrow=1)
```

```{r, fig.width=10, fig.height=3, echo=FALSE}
pcontourLengthLSD = ggplot(dfTrain, aes(classification, contourLengthLSD, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("contourLengthLSD") + theme(legend.position = "none")

pcontourAvgLengthLSD = ggplot(dfTrain, aes(classification, contourAvgLengthLSD, fill=factor(classification))) +   geom_boxplot() + guides(fill=guide_legend(title="Compression Level")) + ggtitle("contourAvgLengthLSD") + theme(legend.position = "none")

pempty = ggplot() +
    theme_void() +
    geom_text(aes(0,0,label=''))

grid.arrange(pcontourLengthLSD, pcontourAvgLengthLSD, pempty, nrow=1)
```

```{r}
s.df = read_csv("../data/standardizeddf.csv")
```

Comparing medium and high compression means:

```{r}
print(paste("sum:", t.test(s.df$sum[s.df$classification=='high'], s.df$sum[s.df$classification=='med'])$p.value))

print(paste("norm:", t.test(s.df$norm[s.df$classification=='high'], s.df$norm[s.df$classification=='med'])$p.value))

print(paste("q1:", t.test(s.df$q1[s.df$classification=='high'], s.df$q1[s.df$classification=='med'])$p.value))

print(paste("q3:", t.test(s.df$q3[s.df$classification=='high'], s.df$q3[s.df$classification=='med'])$p.value))

print(paste("iqr:", t.test(s.df$iqr[s.df$classification=='high'], s.df$iqr[s.df$classification=='med'])$p.value))

print(paste("min:", t.test(s.df$min[s.df$classification=='high'], s.df$min[s.df$classification=='med'])$p.value))

print(paste("max:", t.test(s.df$max[s.df$classification=='high'], s.df$max[s.df$classification=='med'])$p.value))

print(paste("std:", t.test(s.df$std[s.df$classification=='high'], s.df$std[s.df$classification=='med'])$p.value))

print(paste("mean:", t.test(s.df$mean[s.df$classification=='high'], s.df$mean[s.df$classification=='med'])$p.value))

print(paste("med:", t.test(s.df$med[s.df$classification=='high'], s.df$med[s.df$classification=='med'])$p.value))

print(paste("range:", t.test(s.df$range[s.df$classification=='high'], s.df$range[s.df$classification=='med'])$p.value))
```

Comparing medium and high compression means:

```{r}
print(paste("zeroes:", t.test(s.df$zeroes[s.df$classification=='high'], s.df$zeroes[s.df$classification=='med'])$p.value))
```

```{r}
print(paste("aboveMeanCount, low/medium:", t.test(s.df$aboveMeanCount[s.df$classification=='low'], s.df$aboveMeanCount[s.df$classification=='med'])$p.value))

print(paste("aboveMeanCount, low/high:", t.test(s.df$aboveMeanCount[s.df$classification=='high'], s.df$aboveMeanCount[s.df$classification=='low'])$p.value))

print(paste("aboveMeanCount, medium/high:", t.test(s.df$aboveMeanCount[s.df$classification=='high'], s.df$aboveMeanCount[s.df$classification=='med'])$p.value))

print(paste("skew, low/medium:", t.test(s.df$skew[s.df$classification=='low'], s.df$skew[s.df$classification=='med'])$p.value))

print(paste("skew, low/high:", t.test(s.df$skew[s.df$classification=='high'], s.df$skew[s.df$classification=='low'])$p.value))

print(paste("skew, medium/high:", t.test(s.df$skew[s.df$classification=='high'], s.df$skew[s.df$classification=='med'])$p.value))

print(paste("kurtosis, low/medium:", t.test(s.df$kurtosis[s.df$classification=='low'], s.df$kurtosis[s.df$classification=='med'])$p.value))

print(paste("kurtosis, low/high:", t.test(s.df$kurtosis[s.df$classification=='high'], s.df$kurtosis[s.df$classification=='low'])$p.value))

print(paste("kurtosis, medium/high:", t.test(s.df$kurtosis[s.df$classification=='high'], s.df$kurtosis[s.df$classification=='med'])$p.value))

print(paste("entropy, low/medium:", t.test(s.df$entropy[s.df$classification=='low'], s.df$entropy[s.df$classification=='med'])$p.value))

print(paste("entropy, low/high:", t.test(s.df$entropy[s.df$classification=='high'], s.df$entropy[s.df$classification=='low'])$p.value))

print(paste("entropy, medium/high:", t.test(s.df$entropy[s.df$classification=='high'], s.df$entropy[s.df$classification=='med'])$p.value))

print(paste("contourAvgLength, low/medium:", t.test(s.df$contourAvgLength[s.df$classification=='low'], s.df$contourAvgLength[s.df$classification=='med'])$p.value))

print(paste("contourAvgLength, low/high:", t.test(s.df$contourAvgLength[s.df$classification=='high'], s.df$contourAvgLength[s.df$classification=='low'])$p.value))

print(paste("contourAvgLength, medium/high:", t.test(s.df$contourAvgLength[s.df$classification=='high'], s.df$contourAvgLength[s.df$classification=='med'])$p.value))

print(paste("contourCountLSD, low/medium:", t.test(s.df$contourCountLSD[s.df$classification=='low'], s.df$contourCountLSD[s.df$classification=='med'])$p.value))

print(paste("contourCountLSD, low/high:", t.test(s.df$contourCountLSD[s.df$classification=='high'], s.df$contourCountLSD[s.df$classification=='low'])$p.value))

print(paste("contourCountLSD, medium/high:", t.test(s.df$contourCountLSD[s.df$classification=='high'], s.df$contourCountLSD[s.df$classification=='med'])$p.value))

print(paste("contourLengthLSD, low/medium:", t.test(s.df$contourLengthLSD[s.df$classification=='low'], s.df$contourLengthLSD[s.df$classification=='med'])$p.value))

print(paste("contourLengthLSD, low/high:", t.test(s.df$contourLengthLSD[s.df$classification=='high'], s.df$contourLengthLSD[s.df$classification=='low'])$p.value))

print(paste("contourLengthLSD, medium/high:", t.test(s.df$contourLengthLSD[s.df$classification=='high'], s.df$contourLengthLSD[s.df$classification=='med'])$p.value))

print(paste("contourAvgLengthLSD, low/medium:", t.test(s.df$contourAvgLengthLSD[s.df$classification=='low'], s.df$contourAvgLengthLSD[s.df$classification=='med'])$p.value))

print(paste("contourAvgLengthLSD, low/high:", t.test(s.df$contourAvgLengthLSD[s.df$classification=='high'], s.df$contourAvgLengthLSD[s.df$classification=='low'])$p.value))

print(paste("contourAvgLengthLSD, medium/high:", t.test(s.df$contourAvgLengthLSD[s.df$classification=='high'], s.df$contourAvgLengthLSD[s.df$classification=='med'])$p.value))
```

Correlation

```{r}
c.df = df %>% dplyr::select(sum,norm,min,max,q1,q3,iqr,mean,med,std,range,skew,kurtosis,zeroes,aboveMeanCount,entropy)
cormat <- round(cor(c.df),2)

melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()
```

```{r}
c.contour.df = df %>% dplyr::select(contourCountLSD,contourAvgLength,contourLengthLSD,contourAvgLengthLSD)
cor(c.contour.df)
cormat <- round(cor(c.contour.df),2)

melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()
```



